### ISSUE TITLE
PIP can't find receptor_utils

### ISSUE THREAD

**Issue by scharch** [williamdlees/receptor_utils#2]
```
>$ pip install receptor_utils
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement receptor_utils
ERROR: No matching distribution found for receptor_utils
```

**Comment by williamdlees** [comment]
The package is receptor-utils not receptor_utils. Sorry, this is a bit annoying, please let me know if I’ve got it wrong in the documentation somewhere. I think I had to use the hyphen because pip doesn’t like underscores, there was some issue like that.

**Comment by scharch** [comment]
I've tried both, same error message.
FWIW, it has the underscore here: https://airr-community.github.io/ogrdbstats/_build/html/examples/gapped_v.html#gapped-v

**Comment by williamdlees** [comment]
I think pip might mean that it can’t find a version that’s compatible with the version of python you have installed (the package requires >= 3.9). 

You might also want to try updating pip

 

pip install --verbose receptor-utils

 

should give you more info

 

From: Chaim Schramm ***@***.***> 
Sent: Wednesday, February 14, 2024 2:53 AM
To: williamdlees/receptor_utils ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [williamdlees/receptor_utils] PIP can't find receptor_utils (Issue #2)

 

>$ pip install receptor_utils
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement receptor_utils
ERROR: No matching distribution found for receptor_utils

**Comment by scharch** [comment]
Yes, that was it, I was using Python 3.6. On Python 3.9 it installs correctly. Thanks!
